# Header

menu:
  主页: /
  技术: /categories/tech/
  随笔: /categories/essay/
  

# SubNav
subnav:
  bilibili: "https://space.bilibili.com/6083595"
  zhihu: "http://zhihu.com/people/yvonshong"
  github: "http://github.com/yvonshong"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  mail: "mailto:yvon@shong.win"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
# url: http://www.yvonshong.com/blog
# root: /blog/
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: false
# 数学公式
mathjax: true
# 是否在新窗口打开链接
open_in_new: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '人民币版的赞'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
# alipay: https://i.loli.net/2020/10/28/8jJiNGcROCedwEA.png
# 微信二维码图片地址
weixin: https://i.loli.net/2020/10/28/It31kXcofTA9UB2.png

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '无目录'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: https://i.loli.net/2020/10/28/HAbatdcnuM37PKf.png

#你的头像url
avatar: https://i.loli.net/2020/10/28/HAbatdcnuM37PKf.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4acaa8'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  aboutme: '关于我'
  friends: '友链'

aboutme: 自动驾驶从业者🤖 | Hesai Tech<br>早稻田修士🌸 | Waseda University<br>vlogger🎥 | B站id yvonshong <br>少年热忱🙋🏻‍♂️

friends: 
  # Yvon's Horizon | 知乎专栏: https://zhuanlan.zhihu.com/yvon-horizon
  # 微软大法好 | 知乎专栏: https://zhuanlan.zhihu.com/microsoft
  知乎专栏 | 自律走行  : https://zhuanlan.zhihu.com/jiritsu-soko
  # vlog 合辑 | bilibili: https://space.bilibili.com/6083595
  禾赛科技 | Hesai Tech: https://www.hesaitech.com
  图森未来 | TuSimple: https://tusimple.com
  # Wondergate | 奇阵科技: http://wondergate.io/
  # ci123 | 育儿网: http://ippclub.org/
  早稻田大学 | Waseda University: http://www.waseda.jp
  东南大学 | Southeast University: http://www.seu.edu.cn
  成都七中 | Chengdu No.7 Middle High School: http://www.cdqz.net
  # asamaedu | 浅间留学: http://asamaedu.com
  泡泡机器人 | PaoPaoRobot: http://paopaorobot.org/
  微软校园精英 | Microsoft Student Partner: https://studentambassadors.microsoft.com/
  # ippclub | I++俱乐部: http://ippclub.org/
