clone_depth: 5
environment:
 access_token:
    secure: a5IFtQG1IJD1vNEkVFh5rN6xPEpFT6AbjUKx1cwouZEaxRJQG2fw4uKGX2fLapxM

install:
- node --version
- npm --version
- npm install npm@latest -g
- npm cache clean -f
- npm install -g n
- n stable
- node --version
- npm --version
- npm install
- npm install hexo-cli -g
- npm i hexo-generator-json-content --save
- npm install markdown-it-checkbox --save
build_script:
- hexo generate -f


artifacts:
- path: public
on_success:
- echo https://$($env:access_token):x-oauth-basic@github.com $env:USERPROFILE/.git-credentials
- git config --global credential.helper store
- git config --global user.email "%GIT_USER_EMAIL%"
- git config --global user.name "%GIT_USER_NAME%"
- git clone --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%/static-site
- cd %TEMP%/static-site
- rm -rf !(.git) 
- cp -rf %APPVEYOR_BUILD_FOLDER%/public %TEMP%/static-site
- echo www.shong.win >> CNAME
- npm i hexo-generator-json-content --save
- git add -A
- git commit -m "Update Static Site" 
- git push origin %TARGET_BRANCH%
- appveyor AddMessage "Static Site Updated"